<?php

declare(strict_types=1);

final class AiProviderService
{
    public function __construct(private ProviderVaultRepository $vault)
    {
    }

    public function resolve(string $requestedProvider): array
    {
        $requestedProvider = sanitize_key($requestedProvider ?: 'default');
        $vault = $this->vault->publicList();

        if ($requestedProvider === 'default' || $requestedProvider === '') {
            $requestedProvider = $vault['default_provider'] ?? 'local_rule_engine';
        }

        if ($requestedProvider === 'local_rule_engine') {
            return [
                'key' => 'local_rule_engine',
                'name' => 'Local Rule Engine',
                'mode' => 'local',
                'note' => 'The local rule-based engine generated this output without sending data to an external provider.',
            ];
        }

        $provider = $vault['providers'][$requestedProvider] ?? null;
        if (!$provider || empty($provider['enabled'])) {
            return [
                'key' => 'local_rule_engine',
                'name' => 'Local Rule Engine',
                'mode' => 'fallback',
                'note' => 'Requested provider is unavailable or disabled. The local rule-based engine was used as a safe fallback.',
            ];
        }

        return [
            'key' => $requestedProvider,
            'name' => $provider['name'] ?? $requestedProvider,
            'type' => $provider['type'] ?? 'custom',
            'model' => $provider['default_model'] ?? '',
            'mode' => 'external_ready',
            'note' => 'External provider is configured. Live AI generation will be attempted.',
        ];
    }

    public function generate(string $requestedProvider, array $input, array $draftOutput): array
    {
        $requestedProvider = sanitize_key($requestedProvider ?: 'default');
        $vault = $this->vault->vault();

        if ($requestedProvider === 'default' || $requestedProvider === '') {
            $requestedProvider = sanitize_key((string)($vault['default_provider'] ?? 'local_rule_engine'));
        }

        if ($requestedProvider === '' || $requestedProvider === 'local_rule_engine') {
            return [
                'used_external' => false,
                'output' => $draftOutput,
                'note' => 'Local Rule Engine selected.',
            ];
        }

        $provider = $vault['providers'][$requestedProvider] ?? null;
        if (!$provider || empty($provider['enabled'])) {
            $draftOutput['provider']['mode'] = 'fallback';
            $draftOutput['provider']['note'] = 'External provider is disabled or missing. Local Rule Engine fallback was used.';
            return ['used_external' => false, 'output' => $draftOutput, 'note' => $draftOutput['provider']['note']];
        }

        try {
            $apiKey = $this->vault->getDecryptedKey($requestedProvider);
            if ($apiKey === '') {
                throw new RuntimeException('API key is missing or could not be decrypted.');
            }

            $model = trim((string)($provider['default_model'] ?? ''));
            if ($model === '' || $model === 'set-your-model') {
                throw new RuntimeException('Default model name is missing. Add the model name in Provider Vault.');
            }

            $content = $this->callProvider($provider, $apiKey, $model, $input, $draftOutput);
            $aiData = $this->parseJsonResponse($content);

            $safeProvider = [
                'key' => $requestedProvider,
                'name' => $provider['name'] ?? $requestedProvider,
                'type' => $provider['type'] ?? 'custom',
                'model' => $model,
                'mode' => 'live_external',
                'note' => 'Generated by live AI provider: ' . (($provider['name'] ?? $requestedProvider)) . ' / ' . $model . '.',
            ];

            $output = $draftOutput;
            foreach (['improved_prompt', 'short_prompt', 'negative_prompt', 'english_prompt', 'why_stronger', 'warning'] as $field) {
                if (isset($aiData[$field]) && is_string($aiData[$field]) && trim($aiData[$field]) !== '') {
                    $output[$field] = trim($aiData[$field]);
                }
            }

            if (isset($aiData['settings']) && is_array($aiData['settings'])) {
                $output['settings'] = array_merge($output['settings'] ?? [], $aiData['settings']);
            }

            if (isset($aiData['score']) && is_array($aiData['score'])) {
                $output['score'] = array_merge($output['score'] ?? [], $this->normalizeScore($aiData['score']));
            }

            $output['provider'] = $safeProvider;
            $output['generated_by_ai'] = true;

            return [
                'used_external' => true,
                'output' => $output,
                'note' => $safeProvider['note'],
            ];
        } catch (Throwable $e) {
            $draftOutput['provider']['mode'] = 'external_failed_fallback';
            $draftOutput['provider']['note'] = 'Live AI call failed, so the Local Rule Engine output was kept. Error: ' . $e->getMessage();
            $draftOutput['generated_by_ai'] = false;
            return [
                'used_external' => false,
                'output' => $draftOutput,
                'note' => $draftOutput['provider']['note'],
            ];
        }
    }

    private function callProvider(array $provider, string $apiKey, string $model, array $input, array $draftOutput): string
    {
        $type = sanitize_key((string)($provider['type'] ?? 'openai_compatible'));
        $baseUrl = trim((string)($provider['base_url'] ?? ''));

        if ($type === 'gemini') {
            return $this->callGemini($baseUrl, $apiKey, $model, $input, $draftOutput);
        }

        if ($type === 'claude') {
            return $this->callClaude($baseUrl, $apiKey, $model, $input, $draftOutput);
        }

        return $this->callOpenAiCompatible($baseUrl, $apiKey, $model, $input, $draftOutput, $type);
    }

    private function callOpenAiCompatible(string $baseUrl, string $apiKey, string $model, array $input, array $draftOutput, string $type): string
    {
        if ($baseUrl === '') {
            $baseUrl = match ($type) {
                'openai' => 'https://api.openai.com/v1',
                'grok', 'xai' => 'https://api.x.ai/v1',
                default => throw new RuntimeException('Base URL is missing for this OpenAI-compatible provider.'),
            };
        }

        $endpoint = rtrim($baseUrl, '/') . '/chat/completions';
        $headers = [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $apiKey,
        ];

        if ($type === 'openrouter') {
            $headers[] = 'HTTP-Referer: http://localhost';
            $headers[] = 'X-Title: HumanPrompt Studio';
        }

        $payload = [
            'model' => $model,
            'messages' => [
                ['role' => 'system', 'content' => $this->systemPrompt()],
                ['role' => 'user', 'content' => $this->userPrompt($input, $draftOutput)],
            ],
            'temperature' => 0.7,
            'max_tokens' => 2200,
        ];

        $json = $this->httpJson('POST', $endpoint, $headers, $payload);
        $content = $json['choices'][0]['message']['content'] ?? '';
        if (!is_string($content) || trim($content) === '') {
            throw new RuntimeException('Provider returned an empty chat completion response.');
        }

        return $content;
    }

    private function callGemini(string $baseUrl, string $apiKey, string $model, array $input, array $draftOutput): string
    {
        $baseUrl = $baseUrl !== '' ? rtrim($baseUrl, '/') : 'https://generativelanguage.googleapis.com/v1beta';
        $endpoint = $baseUrl . '/models/' . rawurlencode($model) . ':generateContent?key=' . rawurlencode($apiKey);

        $payload = [
            'contents' => [
                [
                    'role' => 'user',
                    'parts' => [
                        ['text' => $this->systemPrompt() . "\n\n" . $this->userPrompt($input, $draftOutput)],
                    ],
                ],
            ],
            'generationConfig' => [
                'temperature' => 0.7,
                'maxOutputTokens' => 2200,
            ],
        ];

        $json = $this->httpJson('POST', $endpoint, ['Content-Type: application/json'], $payload);
        $content = $json['candidates'][0]['content']['parts'][0]['text'] ?? '';
        if (!is_string($content) || trim($content) === '') {
            throw new RuntimeException('Gemini returned an empty response.');
        }

        return $content;
    }

    private function callClaude(string $baseUrl, string $apiKey, string $model, array $input, array $draftOutput): string
    {
        $baseUrl = $baseUrl !== '' ? rtrim($baseUrl, '/') : 'https://api.anthropic.com/v1';
        $endpoint = $baseUrl . '/messages';

        $payload = [
            'model' => $model,
            'max_tokens' => 2200,
            'temperature' => 0.7,
            'system' => $this->systemPrompt(),
            'messages' => [
                ['role' => 'user', 'content' => $this->userPrompt($input, $draftOutput)],
            ],
        ];

        $json = $this->httpJson('POST', $endpoint, [
            'Content-Type: application/json',
            'x-api-key: ' . $apiKey,
            'anthropic-version: 2023-06-01',
        ], $payload);

        $content = $json['content'][0]['text'] ?? '';
        if (!is_string($content) || trim($content) === '') {
            throw new RuntimeException('Claude returned an empty response.');
        }

        return $content;
    }

    private function systemPrompt(): string
    {
        return <<<'PROMPT'
You are HumanPrompt Studio's live AI prompt director.

Your job is to improve any user request into a direct, paste-ready instruction for the next AI/tool. The request may be for an advertisement, image, video, website, code, article, study, comparison, plan, PRD, lesson, analysis, or any other AI task.

CRITICAL OUTPUT CONTRACT:
1. The improved_prompt must be the final command itself, not a description of a prompt.
2. Do not echo the original request as a separate header such as "Original request:" or "الطلب الأصلي:".
3. Do not start with "Convert this request", "Turn this into a prompt", "حوّل الطلب التالي", or similar meta-instructions.
4. Do not include meta lines like "Final output: ready-to-use prompt", "Prompt:", "برومبت:", or "الناتج النهائي".
5. Start directly with an expert role and task instruction: "Act as...", "Design...", "Create...", "Analyze...", "Write...", "Build...", "تصرّف كـ...", "صمّم...", "حلّل...", "اكتب...", or "ابنِ...".
6. Use the same language as the original request when selected_language is Auto. Do not mix English labels into Arabic output unless the term is a common tool name like Figma, Webflow, API, CTA, UX, UI, SEO.
7. Keep the improved_prompt concise but complete. Prefer 180-350 words unless output_style is deep_professional_prompt or the task is complex.
8. Avoid bloated mechanical lists. Use only the details that actually improve the output.
9. Do not force Jordan, local-market language, brand profiles, prices, awards, company history, or country-specific claims unless the user explicitly provided them.
10. Anti-generic visual constraints should be adaptive and concise. Do not dump every negative pattern into the improved prompt. Put the full blacklist in negative_prompt if needed.
11. For non-visual tasks such as research, planning, code, or articles, focus on methodology, structure, verification, edge cases, and deliverables instead of visual anti-AI language.
12. If english_spelling_correction is enabled, use corrected_user_prompt as the main source while preserving any important details from original_user_prompt.

OUTPUT GOAL RULES:
- improve_prompt: improved_prompt must be a better prompt/instruction for another AI/tool.
- generate_final_content: improved_prompt must be the final content itself, not a prompt. Example: final Facebook ad copy, final article draft, final analysis, final plan, final code spec, etc.
- brief_plus_prompt: improved_prompt should include a compact brief followed by the final paste-ready prompt.
- analyze_request: improved_prompt should analyze the request, identify missing details, assumptions, risks, and the recommended best prompt.
- create_variations: improved_prompt should provide multiple improved prompt versions or final content variations, depending on the task.

OUTPUT STYLE RULES:
- direct_prompt: short direct command with minimal sections.
- structured_prompt: clear sections and numbered deliverables.
- short_prompt: very compact version, usually 40-90 words.
- deep_professional_prompt: detailed professional brief with audience, goal, constraints, deliverables, and quality rules.
- tool_specific_prompt: adapt wording and structure to selected_platform/target_tool such as Facebook, Canva, Figma, Midjourney, Veo, Webflow, Framer, ChatGPT, Claude, or Gemini.

Prompt structures by type:
- Ad/campaign: audience, offer, pain point, message hierarchy, headline options, CTA, visual/copy direction, platform fit, concise negative patterns.
- Image/design: subject, context, composition, style, lighting, materials, typography, aspect ratio, negative prompt.
- Video: scene, shot sequence, camera movement, lighting, pacing, duration, audio/mood if useful, negative prompt.
- Website/UI: goal, sections, UX, layout, colors, typography, content expectations, responsive behavior, conversion path, avoid generic templates.
- Article/content: user intent, reader, outline, H1/H2/H3, examples, evidence rules, SEO fields, warnings for changing facts.
- Code/software: goal, expected behavior, architecture, files, data/API contract, security, edge cases, acceptance criteria, tests.
- Study/research/planning: objective, key questions, methodology, comparison criteria, sections, risks, assumptions, recommendation format, action plan.
- General: objective, audience, context, output format, constraints, quality rules, examples, final deliverable.

Return valid JSON only. No markdown fences.

Required JSON fields:
{
  "improved_prompt": "The final paste-ready command only. No meta prompt wording and no original request header.",
  "short_prompt": "A shorter paste-ready version.",
  "negative_prompt": "Concise constraints/negative prompt in the same language as the user when possible.",
  "english_prompt": "English version of improved_prompt, or same as improved_prompt if already English.",
  "why_stronger": "Short explanation of what was improved.",
  "warning": "A useful warning only if something important is missing; otherwise empty.",
  "settings": {"prompt_type":"...", "format":"...", "style":"..."},
  "score": {"goal_clarity": 0, "style_strength": 0, "anti_ai_strength": 0, "output_specificity": 0, "execution_readiness": 0}
}
PROMPT;
    }

    private function userPrompt(array $input, array $draftOutput): string
    {
        $payload = [
            'original_user_prompt' => $input['original_prompt_raw'] ?? ($input['prompt'] ?? ''),
            'corrected_user_prompt' => $input['prompt'] ?? '',
            'english_spelling_correction' => $input['spell_correction'] ?? null,
            'selected_type' => $input['type'] ?? 'auto',
            'selected_style' => $input['style'] ?? 'auto',
            'selected_output_goal' => $input['output_goal'] ?? 'improve_prompt',
            'selected_output_style' => $input['output_style'] ?? 'structured_prompt',
            'selected_platform' => $input['platform'] ?? 'general',
            'selected_language' => $input['language'] ?? 'Auto',
            'selected_market' => trim((string)($input['market'] ?? '')) ?: 'Global / not specified',
            'selected_project_context' => $input['brand_profile'] ?? 'general_project',
            'local_rule_engine_draft' => $draftOutput,
        ];

        return "Use the following data to produce the final enhanced output. Respect selected_output_goal, selected_output_style, selected_platform, and corrected_user_prompt. Correct the local draft if it misclassified the request or injected an unwanted country/local assumption.\n\n" . json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
    }

    private function parseJsonResponse(string $content): array
    {
        $content = trim($content);
        $content = preg_replace('/^```(?:json)?\s*/i', '', $content) ?? $content;
        $content = preg_replace('/\s*```$/', '', $content) ?? $content;
        $content = trim($content);

        $decoded = json_decode($content, true);
        if (is_array($decoded)) {
            return $decoded;
        }

        $start = strpos($content, '{');
        $end = strrpos($content, '}');
        if ($start !== false && $end !== false && $end > $start) {
            $slice = substr($content, $start, $end - $start + 1);
            $decoded = json_decode($slice, true);
            if (is_array($decoded)) {
                return $decoded;
            }
        }

        return [
            'improved_prompt' => $content,
            'short_prompt' => mb_substr($content, 0, 700),
            'why_stronger' => 'The live provider returned plain text instead of JSON, so HumanPrompt Studio used the raw provider response as the improved prompt.',
            'warning' => 'Provider did not return valid JSON.',
        ];
    }

    private function normalizeScore(array $score): array
    {
        $clean = [];
        foreach ($score as $key => $value) {
            $clean[sanitize_key((string)$key)] = max(0, min(10, (int)$value));
        }
        return $clean;
    }

    private function httpJson(string $method, string $url, array $headers, array $payload): array
    {
        $body = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        if ($body === false) {
            throw new RuntimeException('Could not encode provider request JSON.');
        }

        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            if (!$ch) {
                throw new RuntimeException('Could not initialize cURL.');
            }
            curl_setopt_array($ch, [
                CURLOPT_CUSTOMREQUEST => $method,
                CURLOPT_HTTPHEADER => $headers,
                CURLOPT_POSTFIELDS => $body,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_HEADER => false,
                CURLOPT_TIMEOUT => 75,
                CURLOPT_CONNECTTIMEOUT => 20,
            ]);
            $response = curl_exec($ch);
            $error = curl_error($ch);
            $status = (int)curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
            curl_close($ch);

            if ($response === false) {
                throw new RuntimeException('HTTP request failed: ' . $error);
            }
            return $this->decodeHttpResponse((string)$response, $status);
        }

        $context = stream_context_create([
            'http' => [
                'method' => $method,
                'header' => implode("\r\n", $headers),
                'content' => $body,
                'timeout' => 75,
                'ignore_errors' => true,
            ],
        ]);

        $response = file_get_contents($url, false, $context);
        $status = 0;
        if (isset($http_response_header) && is_array($http_response_header)) {
            foreach ($http_response_header as $headerLine) {
                if (preg_match('/^HTTP\/\S+\s+(\d+)/', $headerLine, $matches)) {
                    $status = (int)$matches[1];
                    break;
                }
            }
        }

        if ($response === false) {
            throw new RuntimeException('HTTP request failed. Enable cURL or allow URL fopen.');
        }

        return $this->decodeHttpResponse((string)$response, $status);
    }

    private function decodeHttpResponse(string $response, int $status): array
    {
        $json = json_decode($response, true);
        if (!is_array($json)) {
            throw new RuntimeException('Provider returned non-JSON response. HTTP status: ' . $status);
        }

        if ($status >= 400) {
            $message = $json['error']['message'] ?? $json['message'] ?? ('Provider HTTP error ' . $status);
            throw new RuntimeException((string)$message);
        }

        return $json;
    }
}
